# automatically generated by the FlatBuffers compiler, do not modify

# namespace: switchboard

import flatbuffers

class Broadcast(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsBroadcast(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Broadcast()
        x.Init(buf, n + offset)
        return x

    # Broadcast
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Broadcast
    def Text(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def BroadcastStart(builder): builder.StartObject(1)
def BroadcastAddText(builder, text): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(text), 0)
def BroadcastEnd(builder): return builder.EndObject()
