# automatically generated by the FlatBuffers compiler, do not modify

# namespace: switchboard

import flatbuffers

class ViewUpdate(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsViewUpdate(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ViewUpdate()
        x.Init(buf, n + offset)
        return x

    # ViewUpdate
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ViewUpdate
    def Data(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # ViewUpdate
    def DataAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # ViewUpdate
    def DataLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def ViewUpdateStart(builder): builder.StartObject(1)
def ViewUpdateAddData(builder, data): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0)
def ViewUpdateStartDataVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def ViewUpdateEnd(builder): return builder.EndObject()
